Exception: STATUS_ACCESS_VIOLATION at rip=004F88D1182
rax=FFFFFFFFFFFEFDC2 rbx=000006FFFF76C908 rcx=0000000000000001
rdx=000006FFFF3F0010 rsi=00000006008F1230 rdi=000006FFFF83091A
r8 =0000000000000001 r9 =0000000000000000 r10=00000003DC9A2E80
r11=FEFEFEFEFEFEFEFF r12=00000000FFFFFFFF r13=0000000600010AB0
r14=000006FFFF7EFB40 r15=000006FFFF76E250
rbp=0000000600010AB0 rsp=0000000000239370
program=C:\cygwin64\bin\python3.2m.exe, pid 6644, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00600010AB0  004F88D1182 (6FFFF7688D0, 6FFFFEDB3E8, 00180135E14, 00000239460)
00600010AB0  003DC8D0B29 (00600000060, 6FFFFF6F4A0, 003DC92A114, 6FFFFFCA7A0)
00000000000  003DC8D23FE (6FFFFF70D00, 00000000001, 003DC92EEAD, 00600000004)
6FFFF763F70  003DC86B6D2 (00000000000, 00600931058, 003DC88E3F0, 003DC947F20)
003DC9584A0  003DC84A0F9 (003DC9C8ED8, 00000000000, 003DC9584A0, 000FFFFFFFF)
6FFFF768710  003DC85BC6A (003DC9D0198, 003DC9C8ED8, 003DC88ED0E, 00000000000)
003DC9584A0  003DC84A0F9 (003DC846C49, 00600974D68, 003DC9D0198, 003DC88E3F0)
003DC9584A0  003DC88F046 (003DC8893D4, 0060007B027, 6FFFFFDB3E8, 00600943920)
003DC9584A0  003DC84A0F9 (6FFFFE0CED8, 00600971F10, 001800C597D, 00000001540)
00600010AB0  003DC8CE969 (000000001C8, 0060002D530, 0060093F880, 006000AF730)
00600010AB0  003DC8D1BE1 (6FFFF8FAAB8, 0000000006A, 003DC90032D, 6FFFFDF9C68)
00000000000  003DC8D23FE (000000001B8, 0060002D530, 006009337D0, 00600000001)
00600010AB0  003DC8D1B2B (000000001B0, 0060002D530, 006009335F0, 006000AF730)
00600010AB0  003DC8D1BE1 (000000001D8, 0060002D530, 006009333E0, 006007D8910)
00600010AB0  003DC8D1BE1 (006007D8910, 6FFFFFB6538, FAE3F4FD3CFA8ED9, 00600010AB0)
00000000000  003DC8D23FE (00000000200, 0060002D530, 00600161760, 00600000000)
End of stack trace (more stack frames may be present)
